DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "COLÁS"
DEF PLAYERNAME2 EQUS "SATOSHI"
DEF PLAYERNAME3 EQUS "ASH"

DEF RIVALNAME1 EQUS "ASUR"
DEF RIVALNAME2 EQUS "SHIGERU"
DEF RIVALNAME3 EQUS "GARY"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "COLÁS"
DEF PLAYERNAME2 EQUS "SATOSHI"
DEF PLAYERNAME3 EQUS "ASH"

DEF RIVALNAME1 EQUS "ASUR"
DEF RIVALNAME2 EQUS "SHIGERU"
DEF RIVALNAME3 EQUS "GARY"
ENDC
